version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: randomTestSecret
      MYSQL_DATABASE: resources_db
      MYSQL_USER: resourcesClient
      MYSQL_PASSWORD: appResTestPassword
    ports:
      - "3306:3306"
